#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -le 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

# store args into variables
file_path=$1
ip=$2
username=$3
ssh_key_path=$4
binding='@'

scp "$file_path" "$username""$binding""$ip"":~/" -i "$ssh_key_path"

