#!/usr/bin/env bash
# Display string

echo $$ > /var/run/holbertonscript.pid 

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT, SIGTERM

while :
do
	
	printf "To infinity and beyond\n"
	sleep 2
done
