#!/usr/bin/env bash
# Display string

echo $$ > sudo /var/run/holbertonscript.pid 

trap "echo Y U no love me?!" SIGINT
trap "func" SIGQUIT SIGTERM

func()
{
	if [ -e "/var/run/holbertonscript.pid" ]
	then
		rm /var/run/holbertonscript.pid
	else
		echo "I hate the kill command"
	fi
}

while :
do
	
	printf "To infinity and beyond\n"
	sleep 2
done
