#!/usr/bin/env bash
# print string 10 times using until loop

i=0
while [ $i -le 5 ]
do
	let "i++"
done


python3 << END

with open("/etc/passwd", "r") as f:
	content = f.readlines()

for i in content:
	line = i.split(':')
	print("{}:{}:{}".format(line[0], line[2], line[5]))
END
