#!/usr/bin/env bash
# loops from 1 to 20 and:
#       displays 4 and then bad luck from China for the 4th loop iteration
#	displays 9 and then bad luck from Japan for the 9th loop iteration
#	displays 17 and then bad luck from Italy for the 17th loop iteration

n=1
i=1
e=1
while [ $n -le 720 ]
do
	if [ $i == 60 ]
	then
		echo "Hour: $e"
		i=0
		let "e++"
	else
		echo "$i"
	fi
	let "n++"
	let "i++"
done
