#!/usr/bin/env bash
# Check for files

if [ -e holbertonschool ]
then
    printf "holbertonschool file exists"
    if [ -s holbertonschool ]
    then
        printf "holbertonschool file is not empty"
    else
        printf "holbertonschool file is empty"
    fi
    if [ -f holbertonschool ]
    then
        printf "holbertonschool is a regular file"
    fi
else
    printf "holbertonschool file does not exist"
fi
