#!/usr/bin/env bash
# change user
pkill apache2
chmod 744 /etc/nginx/nginx.conf
sed -i "s/user www-data/#user www-data\nuser nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
